[[constraint]]
  name = "github.com/valyala/fasthttp"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/valyala/bytebufferpool"

[prune]
  go-tests = true
  unused-packages = true
