[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/erikdubbelboer/fasthttp"
  branch = "master"

[[override]]
  name = "github.com/klauspost/compress"
  branch = "master"

[[override]]
  name = "github.com/klauspost/cpuid"
  branch = "master"

[[override]]
  name = "github.com/klauspost/crc32"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
